server:
  port: 8080
  servlet:
    context-path: /demo

spring:
    application:
        name: demo
    main:
        banner-mode: "off"
    datasource:
         dataSourceClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
         username: lifajian
         password: lifajian
         cachePrepStmts: true
         prepStmtCacheSize: 250
         prepStmtCacheSqlLimit: 2048
         useServerPrepStmts: true
         pool: HikariPool
         maximumPoolSize: 20
         minimumIdle: 10
    jpa:
         database-platform: org.hibernate.dialect.MySQLInnoDBDialect
         openInView: false
         dataBase: MYSQL
         show_sql: false
         generate-ddl: false
         hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    data:
         jpa.repositories.enabled: true

